services:
  # --- Frontend Vue.js ---
  progest-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://hgvcprogest-api.davidjunior.dev.br/api"
    image: progest-web:latest
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      # Configuração do DOMÍNIO DO FRONTEND (Corrigido: progrest -> progest)
      - "traefik.http.routers.progest-web.rule=Host(`hgvcprogest.davidjunior.dev.br`)"
      - "traefik.http.routers.progest-web.entrypoints=web,websecure"
      - "traefik.http.routers.progest-web.tls=true"
      - "traefik.http.routers.progest-web.tls.certresolver=letsencrypt"
      # Porta interna onde o frontend roda (80)
      - "traefik.http.services.progest-web.loadbalancer.server.port=80"

# --- Networks ---
networks:
  traefik-public:
    external: true
