services:
  # --- Frontend Vue.js ---
  progest-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://hgvcprogrest-api.davidjunior.dev.br/api"
    image: progest-web:latest
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Configuração do DOMÍNIO DO FRONTEND
      - "traefik.http.routers.progest-web.rule=Host(`hgvcprogrest.davidjunior.dev.br`)"
      - "traefik.http.routers.progest-web.entrypoints=web"
      # Porta interna onde o frontend roda (80)
      - "traefik.http.services.progest-web.loadbalancer.server.port=80"

# --- Networks ---
networks:
  traefik-public:
    external: true
